# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/hyreos/Documentos/git/CMake/bin/cmake

# The command to remove a file.
RM = /home/hyreos/Documentos/git/CMake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hyreos/Documentos/waifu-content

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hyreos/Documentos/waifu-content

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/hyreos/Documentos/git/CMake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/hyreos/Documentos/git/CMake/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hyreos/Documentos/waifu-content/CMakeFiles /home/hyreos/Documentos/waifu-content/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hyreos/Documentos/waifu-content/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kotori

# Build rule for target.
kotori: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kotori
.PHONY : kotori

# fast build rule for target.
kotori/fast:
	$(MAKE) -f CMakeFiles/kotori.dir/build.make CMakeFiles/kotori.dir/build
.PHONY : kotori/fast

#=============================================================================
# Target rules for targets named kernel_core

# Build rule for target.
kernel_core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kernel_core
.PHONY : kernel_core

# fast build rule for target.
kernel_core/fast:
	$(MAKE) -f kernel/CMakeFiles/kernel_core.dir/build.make kernel/CMakeFiles/kernel_core.dir/build
.PHONY : kernel_core/fast

#=============================================================================
# Target rules for targets named chardev

# Build rule for target.
chardev: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chardev
.PHONY : chardev

# fast build rule for target.
chardev/fast:
	$(MAKE) -f kernel/chardev/CMakeFiles/chardev.dir/build.make kernel/chardev/CMakeFiles/chardev.dir/build
.PHONY : chardev/fast

#=============================================================================
# Target rules for targets named rvarch

# Build rule for target.
rvarch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rvarch
.PHONY : rvarch

# fast build rule for target.
rvarch/fast:
	$(MAKE) -f arch/riscv/CMakeFiles/rvarch.dir/build.make arch/riscv/CMakeFiles/rvarch.dir/build
.PHONY : rvarch/fast

#=============================================================================
# Target rules for targets named rvarch_kernel

# Build rule for target.
rvarch_kernel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rvarch_kernel
.PHONY : rvarch_kernel

# fast build rule for target.
rvarch_kernel/fast:
	$(MAKE) -f arch/riscv/kernel/CMakeFiles/rvarch_kernel.dir/build.make arch/riscv/kernel/CMakeFiles/rvarch_kernel.dir/build
.PHONY : rvarch_kernel/fast

#=============================================================================
# Target rules for targets named rvarch_sifive

# Build rule for target.
rvarch_sifive: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rvarch_sifive
.PHONY : rvarch_sifive

# fast build rule for target.
rvarch_sifive/fast:
	$(MAKE) -f arch/riscv/sifive/CMakeFiles/rvarch_sifive.dir/build.make arch/riscv/sifive/CMakeFiles/rvarch_sifive.dir/build
.PHONY : rvarch_sifive/fast

#=============================================================================
# Target rules for targets named arch_riscv_timers

# Build rule for target.
arch_riscv_timers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 arch_riscv_timers
.PHONY : arch_riscv_timers

# fast build rule for target.
arch_riscv_timers/fast:
	$(MAKE) -f arch/riscv/timer/CMakeFiles/arch_riscv_timers.dir/build.make arch/riscv/timer/CMakeFiles/arch_riscv_timers.dir/build
.PHONY : arch_riscv_timers/fast

#=============================================================================
# Target rules for targets named arch_riscv_int

# Build rule for target.
arch_riscv_int: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 arch_riscv_int
.PHONY : arch_riscv_int

# fast build rule for target.
arch_riscv_int/fast:
	$(MAKE) -f arch/riscv/int/CMakeFiles/arch_riscv_int.dir/build.make arch/riscv/int/CMakeFiles/arch_riscv_int.dir/build
.PHONY : arch_riscv_int/fast

#=============================================================================
# Target rules for targets named arch_riscv_spike_htif

# Build rule for target.
arch_riscv_spike_htif: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 arch_riscv_spike_htif
.PHONY : arch_riscv_spike_htif

# fast build rule for target.
arch_riscv_spike_htif/fast:
	$(MAKE) -f arch/riscv/dri/console/spike/CMakeFiles/arch_riscv_spike_htif.dir/build.make arch/riscv/dri/console/spike/CMakeFiles/arch_riscv_spike_htif.dir/build
.PHONY : arch_riscv_spike_htif/fast

arch/riscv/dri/console/spike/htif.obj: arch/riscv/dri/console/spike/htif.cpp.obj

.PHONY : arch/riscv/dri/console/spike/htif.obj

# target to build an object file
arch/riscv/dri/console/spike/htif.cpp.obj:
	$(MAKE) -f CMakeFiles/kotori.dir/build.make CMakeFiles/kotori.dir/arch/riscv/dri/console/spike/htif.cpp.obj
.PHONY : arch/riscv/dri/console/spike/htif.cpp.obj

arch/riscv/dri/console/spike/htif.i: arch/riscv/dri/console/spike/htif.cpp.i

.PHONY : arch/riscv/dri/console/spike/htif.i

# target to preprocess a source file
arch/riscv/dri/console/spike/htif.cpp.i:
	$(MAKE) -f CMakeFiles/kotori.dir/build.make CMakeFiles/kotori.dir/arch/riscv/dri/console/spike/htif.cpp.i
.PHONY : arch/riscv/dri/console/spike/htif.cpp.i

arch/riscv/dri/console/spike/htif.s: arch/riscv/dri/console/spike/htif.cpp.s

.PHONY : arch/riscv/dri/console/spike/htif.s

# target to generate assembly for a file
arch/riscv/dri/console/spike/htif.cpp.s:
	$(MAKE) -f CMakeFiles/kotori.dir/build.make CMakeFiles/kotori.dir/arch/riscv/dri/console/spike/htif.cpp.s
.PHONY : arch/riscv/dri/console/spike/htif.cpp.s

arch/riscv/int/inte.obj: arch/riscv/int/inte.cpp.obj

.PHONY : arch/riscv/int/inte.obj

# target to build an object file
arch/riscv/int/inte.cpp.obj:
	$(MAKE) -f CMakeFiles/kotori.dir/build.make CMakeFiles/kotori.dir/arch/riscv/int/inte.cpp.obj
.PHONY : arch/riscv/int/inte.cpp.obj

arch/riscv/int/inte.i: arch/riscv/int/inte.cpp.i

.PHONY : arch/riscv/int/inte.i

# target to preprocess a source file
arch/riscv/int/inte.cpp.i:
	$(MAKE) -f CMakeFiles/kotori.dir/build.make CMakeFiles/kotori.dir/arch/riscv/int/inte.cpp.i
.PHONY : arch/riscv/int/inte.cpp.i

arch/riscv/int/inte.s: arch/riscv/int/inte.cpp.s

.PHONY : arch/riscv/int/inte.s

# target to generate assembly for a file
arch/riscv/int/inte.cpp.s:
	$(MAKE) -f CMakeFiles/kotori.dir/build.make CMakeFiles/kotori.dir/arch/riscv/int/inte.cpp.s
.PHONY : arch/riscv/int/inte.cpp.s

arch/riscv/kernel/pcb.obj: arch/riscv/kernel/pcb.cpp.obj

.PHONY : arch/riscv/kernel/pcb.obj

# target to build an object file
arch/riscv/kernel/pcb.cpp.obj:
	$(MAKE) -f CMakeFiles/kotori.dir/build.make CMakeFiles/kotori.dir/arch/riscv/kernel/pcb.cpp.obj
.PHONY : arch/riscv/kernel/pcb.cpp.obj

arch/riscv/kernel/pcb.i: arch/riscv/kernel/pcb.cpp.i

.PHONY : arch/riscv/kernel/pcb.i

# target to preprocess a source file
arch/riscv/kernel/pcb.cpp.i:
	$(MAKE) -f CMakeFiles/kotori.dir/build.make CMakeFiles/kotori.dir/arch/riscv/kernel/pcb.cpp.i
.PHONY : arch/riscv/kernel/pcb.cpp.i

arch/riscv/kernel/pcb.s: arch/riscv/kernel/pcb.cpp.s

.PHONY : arch/riscv/kernel/pcb.s

# target to generate assembly for a file
arch/riscv/kernel/pcb.cpp.s:
	$(MAKE) -f CMakeFiles/kotori.dir/build.make CMakeFiles/kotori.dir/arch/riscv/kernel/pcb.cpp.s
.PHONY : arch/riscv/kernel/pcb.cpp.s

arch/riscv/kernel/tcb.obj: arch/riscv/kernel/tcb.cpp.obj

.PHONY : arch/riscv/kernel/tcb.obj

# target to build an object file
arch/riscv/kernel/tcb.cpp.obj:
	$(MAKE) -f CMakeFiles/kotori.dir/build.make CMakeFiles/kotori.dir/arch/riscv/kernel/tcb.cpp.obj
.PHONY : arch/riscv/kernel/tcb.cpp.obj

arch/riscv/kernel/tcb.i: arch/riscv/kernel/tcb.cpp.i

.PHONY : arch/riscv/kernel/tcb.i

# target to preprocess a source file
arch/riscv/kernel/tcb.cpp.i:
	$(MAKE) -f CMakeFiles/kotori.dir/build.make CMakeFiles/kotori.dir/arch/riscv/kernel/tcb.cpp.i
.PHONY : arch/riscv/kernel/tcb.cpp.i

arch/riscv/kernel/tcb.s: arch/riscv/kernel/tcb.cpp.s

.PHONY : arch/riscv/kernel/tcb.s

# target to generate assembly for a file
arch/riscv/kernel/tcb.cpp.s:
	$(MAKE) -f CMakeFiles/kotori.dir/build.make CMakeFiles/kotori.dir/arch/riscv/kernel/tcb.cpp.s
.PHONY : arch/riscv/kernel/tcb.cpp.s

arch/riscv/proc.obj: arch/riscv/proc.cpp.obj

.PHONY : arch/riscv/proc.obj

# target to build an object file
arch/riscv/proc.cpp.obj:
	$(MAKE) -f CMakeFiles/kotori.dir/build.make CMakeFiles/kotori.dir/arch/riscv/proc.cpp.obj
.PHONY : arch/riscv/proc.cpp.obj

arch/riscv/proc.i: arch/riscv/proc.cpp.i

.PHONY : arch/riscv/proc.i

# target to preprocess a source file
arch/riscv/proc.cpp.i:
	$(MAKE) -f CMakeFiles/kotori.dir/build.make CMakeFiles/kotori.dir/arch/riscv/proc.cpp.i
.PHONY : arch/riscv/proc.cpp.i

arch/riscv/proc.s: arch/riscv/proc.cpp.s

.PHONY : arch/riscv/proc.s

# target to generate assembly for a file
arch/riscv/proc.cpp.s:
	$(MAKE) -f CMakeFiles/kotori.dir/build.make CMakeFiles/kotori.dir/arch/riscv/proc.cpp.s
.PHONY : arch/riscv/proc.cpp.s

arch/riscv/sifive/serial.obj: arch/riscv/sifive/serial.cpp.obj

.PHONY : arch/riscv/sifive/serial.obj

# target to build an object file
arch/riscv/sifive/serial.cpp.obj:
	$(MAKE) -f CMakeFiles/kotori.dir/build.make CMakeFiles/kotori.dir/arch/riscv/sifive/serial.cpp.obj
.PHONY : arch/riscv/sifive/serial.cpp.obj

arch/riscv/sifive/serial.i: arch/riscv/sifive/serial.cpp.i

.PHONY : arch/riscv/sifive/serial.i

# target to preprocess a source file
arch/riscv/sifive/serial.cpp.i:
	$(MAKE) -f CMakeFiles/kotori.dir/build.make CMakeFiles/kotori.dir/arch/riscv/sifive/serial.cpp.i
.PHONY : arch/riscv/sifive/serial.cpp.i

arch/riscv/sifive/serial.s: arch/riscv/sifive/serial.cpp.s

.PHONY : arch/riscv/sifive/serial.s

# target to generate assembly for a file
arch/riscv/sifive/serial.cpp.s:
	$(MAKE) -f CMakeFiles/kotori.dir/build.make CMakeFiles/kotori.dir/arch/riscv/sifive/serial.cpp.s
.PHONY : arch/riscv/sifive/serial.cpp.s

arch/riscv/timer/rtc.obj: arch/riscv/timer/rtc.cpp.obj

.PHONY : arch/riscv/timer/rtc.obj

# target to build an object file
arch/riscv/timer/rtc.cpp.obj:
	$(MAKE) -f CMakeFiles/kotori.dir/build.make CMakeFiles/kotori.dir/arch/riscv/timer/rtc.cpp.obj
.PHONY : arch/riscv/timer/rtc.cpp.obj

arch/riscv/timer/rtc.i: arch/riscv/timer/rtc.cpp.i

.PHONY : arch/riscv/timer/rtc.i

# target to preprocess a source file
arch/riscv/timer/rtc.cpp.i:
	$(MAKE) -f CMakeFiles/kotori.dir/build.make CMakeFiles/kotori.dir/arch/riscv/timer/rtc.cpp.i
.PHONY : arch/riscv/timer/rtc.cpp.i

arch/riscv/timer/rtc.s: arch/riscv/timer/rtc.cpp.s

.PHONY : arch/riscv/timer/rtc.s

# target to generate assembly for a file
arch/riscv/timer/rtc.cpp.s:
	$(MAKE) -f CMakeFiles/kotori.dir/build.make CMakeFiles/kotori.dir/arch/riscv/timer/rtc.cpp.s
.PHONY : arch/riscv/timer/rtc.cpp.s

kernel/chardev/uart.obj: kernel/chardev/uart.cpp.obj

.PHONY : kernel/chardev/uart.obj

# target to build an object file
kernel/chardev/uart.cpp.obj:
	$(MAKE) -f CMakeFiles/kotori.dir/build.make CMakeFiles/kotori.dir/kernel/chardev/uart.cpp.obj
.PHONY : kernel/chardev/uart.cpp.obj

kernel/chardev/uart.i: kernel/chardev/uart.cpp.i

.PHONY : kernel/chardev/uart.i

# target to preprocess a source file
kernel/chardev/uart.cpp.i:
	$(MAKE) -f CMakeFiles/kotori.dir/build.make CMakeFiles/kotori.dir/kernel/chardev/uart.cpp.i
.PHONY : kernel/chardev/uart.cpp.i

kernel/chardev/uart.s: kernel/chardev/uart.cpp.s

.PHONY : kernel/chardev/uart.s

# target to generate assembly for a file
kernel/chardev/uart.cpp.s:
	$(MAKE) -f CMakeFiles/kotori.dir/build.make CMakeFiles/kotori.dir/kernel/chardev/uart.cpp.s
.PHONY : kernel/chardev/uart.cpp.s

kernel/utility.obj: kernel/utility.cpp.obj

.PHONY : kernel/utility.obj

# target to build an object file
kernel/utility.cpp.obj:
	$(MAKE) -f CMakeFiles/kotori.dir/build.make CMakeFiles/kotori.dir/kernel/utility.cpp.obj
.PHONY : kernel/utility.cpp.obj

kernel/utility.i: kernel/utility.cpp.i

.PHONY : kernel/utility.i

# target to preprocess a source file
kernel/utility.cpp.i:
	$(MAKE) -f CMakeFiles/kotori.dir/build.make CMakeFiles/kotori.dir/kernel/utility.cpp.i
.PHONY : kernel/utility.cpp.i

kernel/utility.s: kernel/utility.cpp.s

.PHONY : kernel/utility.s

# target to generate assembly for a file
kernel/utility.cpp.s:
	$(MAKE) -f CMakeFiles/kotori.dir/build.make CMakeFiles/kotori.dir/kernel/utility.cpp.s
.PHONY : kernel/utility.cpp.s

main.obj: main.cpp.obj

.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) -f CMakeFiles/kotori.dir/build.make CMakeFiles/kotori.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/kotori.dir/build.make CMakeFiles/kotori.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/kotori.dir/build.make CMakeFiles/kotori.dir/main.cpp.s
.PHONY : main.cpp.s

startup.obj: startup.S.obj

.PHONY : startup.obj

# target to build an object file
startup.S.obj:
	$(MAKE) -f CMakeFiles/kotori.dir/build.make CMakeFiles/kotori.dir/startup.S.obj
.PHONY : startup.S.obj

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... kotori"
	@echo "... kernel_core"
	@echo "... chardev"
	@echo "... rvarch"
	@echo "... rvarch_kernel"
	@echo "... rvarch_sifive"
	@echo "... arch_riscv_timers"
	@echo "... arch_riscv_int"
	@echo "... arch_riscv_spike_htif"
	@echo "... arch/riscv/dri/console/spike/htif.obj"
	@echo "... arch/riscv/dri/console/spike/htif.i"
	@echo "... arch/riscv/dri/console/spike/htif.s"
	@echo "... arch/riscv/int/inte.obj"
	@echo "... arch/riscv/int/inte.i"
	@echo "... arch/riscv/int/inte.s"
	@echo "... arch/riscv/kernel/pcb.obj"
	@echo "... arch/riscv/kernel/pcb.i"
	@echo "... arch/riscv/kernel/pcb.s"
	@echo "... arch/riscv/kernel/tcb.obj"
	@echo "... arch/riscv/kernel/tcb.i"
	@echo "... arch/riscv/kernel/tcb.s"
	@echo "... arch/riscv/proc.obj"
	@echo "... arch/riscv/proc.i"
	@echo "... arch/riscv/proc.s"
	@echo "... arch/riscv/sifive/serial.obj"
	@echo "... arch/riscv/sifive/serial.i"
	@echo "... arch/riscv/sifive/serial.s"
	@echo "... arch/riscv/timer/rtc.obj"
	@echo "... arch/riscv/timer/rtc.i"
	@echo "... arch/riscv/timer/rtc.s"
	@echo "... kernel/chardev/uart.obj"
	@echo "... kernel/chardev/uart.i"
	@echo "... kernel/chardev/uart.s"
	@echo "... kernel/utility.obj"
	@echo "... kernel/utility.i"
	@echo "... kernel/utility.s"
	@echo "... main.obj"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... startup.obj"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

